# Generated by Django 5.0.4 on 2024-05-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_is_on_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_on_header',
        ),
    ]
