# Generated by Django 5.0.4 on 2024-05-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_paid_amount_remove_order_payment_intent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent',
        ),
    ]
